---
- name: Install Apache webserver
  hosts: dev
  tasks:
    - name: Installing apache server
      yum:
        name: httpd
        state: present

    - name: Copying index.html file
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html

    - name: starting the service
      service:
        name: httpd
        state: started
